# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 11:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infokala', '0004_populate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.CharField(max_length=64, unique=True, verbose_name='tunniste'),
        ),
    ]
