# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infokala', '0007_messagetype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='slug',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='tunniste'),
        ),
    ]
