# Generated by Django 4.2.2 on 2023-06-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infokala', '0008_no_empty_slugs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='infokala_me_event_s_35755f_idx',
            old_fields=('event_slug', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='state',
            new_name='infokala_st_workflo_a3c344_idx',
            old_fields=('workflow', 'order'),
        ),
    ]
